version: 2

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140  # Increased from 120 for complex expressions
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  funlen:
    lines: 80  # Increased from 60 for coordinator methods
    statements: 50  # Increased from 40 for complex business logic

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - goconst
        - gocyclo
        - lll
        - dupl

    # Allow longer function names in main functions
    - path: cmd/.*\.go
      linters:
        - funlen

    # Allow magic strings in test files
    - path: test/.*\.go
      linters:
        - goconst

    # Allow unused parameters in interface implementations
    - path: .*\.go
      linters:
        - unparam
      text: "result 0 .* is always nil"

    # Allow os.Exit in main functions
    - path: cmd/.*\.go
      linters:
        - gocritic
      text: "exitAfterDefer"

run:
  timeout: 5m
  tests: true
